version: '2.1'

services:
  tomcat:
    image: iseries-app
    build: .
    ports:
      - '8080:8080'
    volumes: 
      - ./target/iSeries-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/iseries.war
    networks:
      - mt-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=iseries
    ports:
      - '3389:3306'
    networks:
      - mt-network
  




volumes:
  mysql-data:
    driver: local
networks:
  mt-network:
    driver: bridge
